### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [xxv/Units#9]
![Screenshot_20220626-122526](https://user-images.githubusercontent.com/59341190/175826469-8e91e22c-0754-48d0-9fc0-36e8813125bb.png)

This app is extremely useful and has a lot of potential. An update to resolve the popup above would be greatly appreciated. Running v1.0 on android v12.

**Comment by buttercookie42** [comment]
This message in itself is purely cosmetic and can be mostly ignored. The actual annoying things are that Android 10 removed support for the legacy menu button, so the main menu can't be easily accessed any more, and Android 14 blocks installation of the app outright unless you install the app via `adb install --bypass-low-target-sdk-block` or have a rooted device to apply alternative workarounds.

I've created an updated version here:
https://github.com/buttercookie42/Units/releases
